kind: CSIVXFlexOS
apiVersion: storage.dell.com/v1
metadata:
  name: powerflex
  namespace: powerflex
spec:
  driver:
    common:
      envs:
        - name: X_CSI_VXFLEXOS_ENABLELISTVOLUMESNAPSHOT
          value: 'false'
        - name: X_CSI_VXFLEXOS_ENABLESNAPSHOTCGDELETE
          value: 'false'
        - name: X_CSI_DEBUG
          value: 'true'
        - name: X_CSI_ALLOW_RWO_MULTI_POD_ACCESS
          value: 'false'
      image: >-
        docker.io/dellemc/csi-vxflexos@sha256:5fda22d6b681579017d593254223298aedfb8000bdb596e71b88b13dfeb5715a
      imagePullPolicy: IfNotPresent
    tlsCertSecret: vxflexos-certs
    configVersion: v2.3.0
    authSecret: vxflexos-creds
    controller:
      envs: null
      nodeSelector: null
      tolerations: null
    dnsPolicy: ClusterFirstWithHostNet
    forceUpdate: false
    fsGroupPolicy: File
    initContainers:
      - envs:
          - name: MDM
            value: '192.168.x.x,192.168.x.x'
        image: >-
          docker.io/dellemc/sdc@sha256:784b3ad7c0d5fbea8267e7e0be1830383f31d6bb57e4626c55cf5d0de344a272
        imagePullPolicy: IfNotPresent
        name: sdc
    node:
      envs: null
      nodeSelector: null
      tolerations: null
    replicas: 1
