apiVersion: v1
kind: Pod
metadata:
  name: powerflextestpod
  namespace: default
spec:
  containers:
  - name: test
    image: docker.io/centos:latest
    command: [ "/bin/sleep", "3600" ]
    volumeMounts:
    - name: pvol0-powerflex
      mountPath: "/data0"
  volumes:
    - name: pvol0-powerflex
      persistentVolumeClaim:
        claimName: pvol0-powerflex
